### ISSUE TITLE
exports: Emojis missing

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-studio-issue-tracker#10]
<img width="407" alt="Screen Shot 2023-07-04 at 4 19 38 PM" src="https://github.com/terrastruct/d2-studio-issue-tracker/assets/3120367/5df33bad-71fa-4d71-be12-3af966c903f5">

**Comment by berniexie** [comment]
this works on dev. I wonder if its because the chromedriver version in the exporter is too low.

**Comment by alixander** [comment]
i think it probably loads too fast before it renders right? @berniexie

**Comment by berniexie** [comment]
I doubt it, it should have significant time to load the emojis. Even if you add an image, and it waits for the image to load first (which I think would take a much longer time), the emoji never loads. I actually think its because the OS we run the exporter on just doesn't support emojis. I can see people online complaining about this on windows 7 which also didn't support emojis. @alixander

**Comment by berniexie** [comment]
I think we could potentially resolve this by adding an emoji font to our exporter. However, those emojis won't match the mac os default emojis. https://fonts.google.com/noto/specimen/Noto+Emoji/glyphs

**Comment by alixander** [comment]
i guess that'd slow down every single export due to waiting for this font to load though right?

not matching isn't an issue, when people use emoji's, i think the only expectation is an equivalent -- e.g. android sending to iphone

but slowing down all exports for the other 99.99% of diagrams that don't have emojis would be bad. I guess we can detect if it's needed by reading all the text and regexing for emoji patterns. but that seems overly complicated for now. let's defer

**Comment by berniexie** [comment]
@alixander if you just add that font to the OS, will it take up a lot of resource time? I think the OS will only try to insert that font if it detects a glyph right? Its kinda like our chinese font.

**Comment by alixander** [comment]
we still load the hans font in our frontend though: https://github.com/terrastruct/src/blob/211af3feaa3e0e83c396cb51855730062d9a8bfb/frontend/src/components/Fonts.scss#L92

but it's worth a try. not sure how to install the font to the export server, if you know how, go for it

**Comment by berniexie** [comment]
@alixander unfortunately I still cannot ssh into anything, but its just copying the font into https://www.internalpointers.com/post/install-new-fonts-linux-command-line

**Comment by alixander** [comment]
worked
