### ISSUE TITLE
on first compile, if shapes moves, show help on positions

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-studio-issue-tracker#17]
the first time a user compiles and sees things move that were moved manually, should show a "What happened to my positions?" modal that explains what autolayout does and how to override it with positioning

**Comment by katwangy** [comment]
need content for "what happened to my positions" modal.

also, what do u think of surfacing up a notification instead? and if they do want to override, it opens up the modal (that way it is less intrusive)

![Screen Shot 2023-08-15 at 2 24 21 PM](https://github.com/terrastruct/d2-studio-issue-tracker/assets/102620103/cbf41a4d-dbcf-451a-9a7b-21043136b5c2)
