### ISSUE TITLE
Link are not highlighted in draw mode

### ISSUE THREAD

**Issue by RootMePLS** [terrastruct/d2-studio-issue-tracker#22]
It's hard to understand where should we click in the text, because links not highlighted

![image](https://github.com/terrastruct/d2-studio-issue-tracker/assets/2705977/4756320d-bcc2-4067-bbce-c257f24a556c)

**Comment by RootMePLS** [comment]
@gavin-ts I see no changes

**Comment by alixander** [comment]
@fishhead108 sorry wasn't deployed. It is now. To be clear, the links aren't underlined by default, only on hover. I believe most markdown implementations don't, e.g.: [link](https://google.com). But it does have a different color. Maybe we should do that too @gavin-ts . Will reuse this issue

**Comment by gavin-ts** [comment]
Yes that is a good point, next deploy should have a highlight color and underline on hover both working with and without hand drawn mode.

**Comment by alixander** [comment]
deployed
