### ISSUE TITLE
debug slack app

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-studio-issue-tracker#45]
seems to be down

**Comment by alixander** [comment]
I wonder if there's a way to make this an automated daily test

**Comment by gavin-ts** [comment]
<img width="498" alt="Screenshot 2023-10-19 at 1 53 49 PM" src="https://github.com/terrastruct/d2-studio-issue-tracker/assets/85081687/af79a73a-b965-4859-9c46-04a60605d52f">

seems to be working for me?

**Comment by alixander** [comment]
@gavin-ts can you try this guy's: https://discord.com/channels/976899413542830181/1019365046486306957/1164504987896922213

**Comment by gavin-ts** [comment]
looks like it isn't working when there are icons
