### ISSUE TITLE
Tables doesn't respect connection to other objects, except Tables

### ISSUE THREAD

**Issue by RootMePLS** [terrastruct/d2-studio-issue-tracker#5]
I'm trying to make a connection row in a Table - some Object. 
But the Table chooses a random string instead of the one I specified in the code.
![image](https://github.com/terrastruct/d2-studio-issue-tracker/assets/2705977/23d52bc2-fe62-4e56-9d9a-b90467e57382)

**Comment by RootMePLS** [comment]
any news on this @alixander ?

**Comment by alixander** [comment]
@fishhead108 not yet, queued todo

**Comment by RootMePLS** [comment]
@alixander any update?
It could really help with the mess like on the picture

![image](https://github.com/terrastruct/d2-studio-issue-tracker/assets/2705977/13dd16ce-ae6d-46bc-9fe6-9438ed652cc9)

**Comment by RootMePLS** [comment]
@alixander any news here?

**Comment by alixander** [comment]
😬 i feel terrible each ping, but we're just so backed up with other deadlined-tasks. will do as soon as there's bandwidth, which rn looks like second week of september. i'm sorry about this and appreciate the reminders.

**Comment by gavin-ts** [comment]
will close once live

**Comment by gavin-ts** [comment]
<img width="1278" alt="Screen Shot 2023-09-05 at 3 40 37 PM" src="https://github.com/terrastruct/d2-studio-issue-tracker/assets/85081687/884a573d-75f3-4cac-9293-c19bcaa9ee10">

**Comment by RootMePLS** [comment]
thank you!
