### ISSUE TITLE
Export PDF not as a png but a vectors 

### ISSUE THREAD

**Issue by Nova38** [terrastruct/d2-studio-issue-tracker#52]
This request is similar to issue #38. D2 has the ability to export it to a svg but d2 studio only generates a png. Generate the diagram as an svg first then a pdf instead of just a png would allow for the diagram to be higher quality. Also, it would allow things like using control-F searching or screen readers as the text would be text and not just an image of text.  I love the D2 studio editor but this feature seems a bit lacking given that the open source tool can generate svg output.

**Comment by Nova38** [comment]
Linkes also don't seem to work when exporting it as a pdf

**Comment by alixander** [comment]
exports as svg work now
